### ISSUE TITLE
Installation with fin throws error for requiring `debug`

### ISSUE THREAD

**Issue by herrbischoff** [fishery/z#6] opened 2016-04-13 14:51 UTC
Here's the log:

```
$ fin z
fin SAYS Installing 1 plugin
         ✔  z                       https://github.com/fishery/z
fish: Unknown command 'debug'
~/.config/fish/conf.d/z.fish (line 18): debug "$Z_CMD $ZO_CMD"
                                        ^
from sourcing file ~/.config/fish/conf.d/z.fish
	called on line 576 of file ~/.config/fish/functions/fin.fish

in function '__fin_plugin_enable'
	called on line 360 of file ~/.config/fish/functions/fin.fish
	with parameter list '/Users/mbischoff/.config/fin/z'

in function '__fin_install'
	called on line 201 of file ~/.config/fish/functions/fin.fish
	with parameter list 'z'

in function 'fin'
	called on standard input
	with parameter list 'z'

fin SAYS Done in 1s 993ms
```

**Comment by jethrokuan** [comment] 2016-04-13 15:08
Right, I think this is because `debug` isn't included as a dependency in fin, but it is in fisherman. I think It's better that I clear off uses for that. Gonna fix it and do a quick push. Thanks for reporting!

**Comment by jethrokuan** [comment] 2016-04-13 15:12
I think I fixed it, now it doesn't have any external dependencies whatsoever. Would love for you to try again. Thanks!

**Comment by jethrokuan** [comment] 2016-04-13 15:30
I face another problem now:

fin only copies only `.fish` files over, which leaves the .awk files behind. Do you think it would be a good idea to put the awk scripts into the fish files?

Or is this a problem that package managers like fin are supposed to solve?

**Comment by herrbischoff** [comment] 2016-04-13 19:56
I tried the updated version and it does not output any error now.

Regarding the awk issue, since `fin` itself uses awk inside the script, I guess going inline would be the way to go.

**Comment by jethrokuan** [comment] 2016-04-14 02:06
this was fixed in fin after talking to @bucaran .

I like my awk files outside, but when I bump into issues again, I'll move them into their .fish files.

**Closed by jethrokuan** 2016-04-14 02:06 UTC

**Comment by bucaran** [comment] 2016-04-14 02:17
@jethrokuan The awk files issue is fixed now, did I miss anything?

**Comment by jethrokuan** [comment] 2016-04-14 02:18
@bucaran nope it's fixed!

**Comment by Perlence** [comment] 2016-08-13 18:59
@jethrokuan @bucaran 

> nope it's fixed!

Is it? I'm confused, awk files are still missing. I'm running fin v7.

**Comment by bucaran** [comment] 2016-08-13 19:13
@Perlence Are you using fisherman or fin?

**Comment by Perlence** [comment] 2016-08-13 19:26
Yep, I'm using fin this time :smile:

**Comment by bucaran** [comment] 2016-08-13 19:54
And what's the problem exactly? I am pretty sure this issue was created based on a very early version of fin, possibly entirely different to the one you are using now :P

**Comment by Perlence** [comment] 2016-08-13 20:10
Yes, I understand, but I looked to find similar issues here, and I decided that this one is looked close enough.

The problem is that after installing `fisherman/z` with fin, it throws an error on invocation:
```
> cd ~/.config/fish
> cat fishfile
fisherman/z
> fin
> z dot
awk: fatal: can't open source file `/home/sviatoslav/.config/fish/functions/z.awk' for reading (No such file or directory)
> ll functions
total 32K
-rw-rw-rw- 1 sviatoslav sviatoslav 7.9K Aug 13 23:03 fin.fish
-rw-rw-r-- 2 sviatoslav sviatoslav 2.0K May 26 19:52 getopts.fish
-rw-rw-r-- 2 sviatoslav sviatoslav  268 Aug  3 15:50 uninstall.fish
-rw-rw-r-- 2 sviatoslav sviatoslav  512 Aug  3 15:50 __z_add.fish
-rw-rw-r-- 2 sviatoslav sviatoslav 1.8K Aug  3 15:50 __z.fish
-rw-rw-r-- 2 sviatoslav sviatoslav 1.2K Aug  3 15:50 __zo.fish
```

Files z.awk and zadd.awk are missing.

**Comment by bucaran** [comment] 2016-08-13 20:26
Gotcha. Yes, fin won't play well with this plugin because it does not copy .awk or any other script files into the functions diretory, only .fish files. 

This is not a problem with fin, it's just how it was designed, for simplicity. See this 
https://github.com/fisherman/fin/issues/5#issuecomment-222481377

**Comment by Perlence** [comment] 2016-08-13 20:37
Ok, I see. So, how would you make this plugin work? Copy awk files yourself, or embed them in a fish file, or something else?

**Comment by bucaran** [comment] 2016-08-13 20:40
If you must use z and fin, then copy the .awk files to the same directory where the .fish files are, possibly ~/.config/fish/functions. The _fin_ way is for plugins that use awk/perl to embed the script in the same file.

I'm glad you are using fin. It's my favorite!

**Comment by Perlence** [comment] 2016-08-13 21:00
Thank you, I'll try one of the approaches :bow:
